repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: end-of-file-fixer
        stages: [commit]
  - repo: local
    hooks:
      - id: conventional-commit
        name: Conventional commit
        description: Check if commits follow the conventional commit specification
        language: system
        entry: ./etc/scripts/check_commit_msg.sh
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        exclude: ^(legacy-backend|tests)/.*$
        files: ^crispy-api/api/.*\.py$
        stages: [commit]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        require_serial: true
        name: Coding style (Black)
        language_version: python3.10
        stages: [commit]
        exclude: ^legacy-backend.*$
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        require_serial: true
        name: isort
        args: ["--profile", "black"]
        stages: [commit]
        exclude: ^legacy-backend.*$
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        require_serial: true
        name: Coding style (flake8)
        stages: [commit]
        exclude: ^legacy-backend.*$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        exclude: ^.github/
        name: Prettier
        stages: [commit]
        additional_dependencies:
          - prettier
          - svelte
